Show queue results
yiisoft/yii-debug-viewer pull request #46
Opened 2022-08-09 20:03 UTC by Sergiayn

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2022-08-09 21:46 UTC, samdark commented on resources/views/queues/view.html
> +        <strong class="titlePushes">Pusched <span>0</span> jobs</strong>
```suggestion
        <strong class="titlePushes">Pushed <span>0</span> jobs</strong>
```

2022-08-09 21:46 UTC, samdark commented on resources/views/queues/summary.html
> +        <span class="yii-debug-toolbar__label" data-key="queue.statuses">0</span>
Could use `title` here to display hints about what these numers mean. Also coloring it differently would be cool.

2022-08-09 21:46 UTC, samdark commented on resources/views/queues/summary.html
> +        link.title = 'Count: processing messages: ' + cMessages + ', pushes: ' + cPushes + ', statuses: ' + cStatuses
Separate titles for each number will likely be more helpful.

2022-08-10 18:42 UTC, rustamwin requested changes

2022-08-10 21:06 UTC, samdark approved these changes

2022-08-10 21:52 UTC, merged

2022-08-10 21:52 UTC, samdark commented
👍